-- ============================================
-- 快捷键提示：which-key.nvim
-- 按 leader 键后弹出分类菜单，显示可用快捷键
-- ============================================

return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    -- 只为下列前缀弹提示；不覆盖所有操作符和文本对象，避免打字时频繁弹窗。
    -- v 模式同时覆盖全局可视映射（如 Sidekick）与 Java 的局部重构映射。
    triggers = {
      { "<leader>", mode = { "n", "v" } },
      { "\\", mode = { "n", "v" } }, -- localleader
      { "g", mode = { "n", "v" } },
      { "z", mode = { "n", "v" } },
      { "[", mode = { "n", "v" } },
      { "]", mode = { "n", "v" } },
      { "<C-w>", mode = { "n" } },
    },
    delay = 300,
    spec = {
      -- 这里只改提示，不创建/重绑按键。前缀区分通用工具、语言能力和专用功能。
      -- 分组名同时覆盖普通/可视模式；没有实际子项的空组由 which-key 自动收起。
      -- 不用 cond 按当前 filetype 判断：cond 在注册时求值，切换文件后不会重新判断。
      {
        mode = { "n", "v" },
        { "<leader>a", group = "通用 · AI CLI" },
        { "<leader>b", group = "通用 · 缓冲区" },
        { "<leader>c", group = "LSP · 代码操作" },
        { "<leader>d", group = "DAP · 调试" },
        { "<leader>f", group = "通用 · 搜索" },
        { "<leader>h", group = "通用 · 速查/消息" },
        { "<leader>r", group = "LSP · 重命名" },
        -- sp 是全局创建入口，不能因为当前不是 Java 文件就隐藏整个 Spring 组。
        { "<leader>s", group = "Spring · 项目/运行" },
        { "<leader>t", group = "通用 · 终端" },
        { "<leader>u", group = "Neovide · 显示" },
        { "<leader>v", group = "通用 · 窗口切分" },
        { "<leader>w", group = "通用 · 保存/退出" },
        { "<leader>G", group = "Java · 代码生成" },
        { "<leader>J", group = "Java · 测试/调试" },
        { "<leader>m", group = "Java · Maven/Gradle" },
        { "<leader>M", group = "Markdown · 美化" },
        { "<leader>o", group = "整理 · 按语言" },
        { "<leader>R", group = "重构 · 按语言" },
      },
      -- 单项提示只覆盖实际已有的普通模式映射，不在可视模式制造虚假入口。
      { "<leader>e", desc = "通用 · 文件树" },
      { "<leader>j", desc = "通用 · 合并下一行" },
      { "<leader>q", desc = "通用 · 关闭窗口" },
      { "<leader>F", desc = "格式化 · 当前文件" },

      { "ZQ", desc = "放弃当前窗口修改并关闭（不自动保存）" },
      { "g", group = "g 前缀 —— 跳转、转换、文件" },
      -- Neovim 内置注释（descriptions 是英文的 "Toggle comment*"，这里覆盖成中文）
      { "gc", desc = "注释/取消注释（可视、可配 motion）" },
      { "gcc", desc = "注释/取消注释当前行" },
      { "ge", desc = "上一个单词末尾" },
      { "gE", desc = "上一个 WORD 末尾" },
      { "gf", desc = "打开光标下文件" },
      { "gF", desc = "打开文件并跳到指定行" },
      { "gh", desc = "悬停文档（LSP）" },
      { "gg", desc = "跳到文件开头" },
      { "g;", desc = "上一个修改位置" },
      { "g,", desc = "下一个修改位置" },
      { "gt", desc = "下一个标签页" },
      { "gT", desc = "上一个标签页" },
      { "gv", desc = "重新选择上次可视区域" },
      { "gu", desc = "小写转换（配合 motion）" },
      { "gU", desc = "大写转换（配合 motion）" },
      { "gA", desc = "跳转到父类/接口实现（Java）" },
      { "gr", group = "LSP：引用 / 重命名 / 代码操作（内置）" },
      -- gr* 是 Neovim 0.12 内置的 LSP 键（本配置故意不覆盖 gr 前缀），
      -- 内置 desc 是英文（vim.lsp.buf.references() 之类），这里覆盖成中文，弹窗才读得懂。
      { "grr", desc = "查找引用（LSP）" },
      { "grn", desc = "重命名符号（LSP）" },
      { "gra", desc = "代码操作（LSP）" },
      { "gri", desc = "跳转到实现（LSP）" },
      { "grt", desc = "跳转到类型定义（LSP）" },
      { "g~", desc = "切换大小写（配合 motion）" },
      { "gq", desc = "格式化选中文本" },
      { "gw", desc = "格式化（光标不动）" },
      { "gn", desc = "向前搜索并选中匹配" },
      { "gN", desc = "向后搜索并选中匹配" },
      -- ⚠ 这几个是**屏幕行**语义（不是"忽略折行"）：g0/g$/gj/gk 在折行内移动
      { "g0", desc = "跳到屏幕行行首" },
      { "g^", desc = "跳到屏幕行行首非空" },
      { "gm", desc = "跳到行中间" },
      { "g$", desc = "跳到屏幕行行尾" },
      { "g_", desc = "跳到行尾非空字符" },
      { "gj", desc = "下移一个屏幕行" },
      { "gk", desc = "上移一个屏幕行" },
      { "gx", desc = "用系统程序打开文件/链接" },
      { "g%", desc = "跳转到行内匹配" },
      { "gI", desc = "在行首插入" },
      { "gD", desc = "跳到文件内全局声明（gd 才是局部）" },
      { "g*", desc = "向后搜索光标单词" },
      { "g#", desc = "向前搜索光标单词" },
      { "g]", desc = "跳转到标签定义" },
      { "g<", desc = "查看上次命令输出" },
      { "g8", desc = "显示 UTF-8 编码字节" },
      { "gd", desc = "跳转到定义（LSP）" },
      { "gi", desc = "跳转到实现（LSP）" },
      { "gR", desc = "跳转到类型定义（LSP）" },
      { "gO", desc = "本文档符号列表（LSP）" },

      -- （原顶层 t / tt / th / tv 条目已删：真实键位是 <leader>tt/th/tv，顶层 t 不触发弹窗）

      { "z", group = "z 前缀 —— 折叠/滚动" },
      { "za", desc = "切换折叠" },
      { "zA", desc = "递归切换折叠" },
      { "zc", desc = "关闭折叠" },
      { "zC", desc = "递归关闭折叠" },
      { "zo", desc = "打开折叠" },
      { "zO", desc = "递归打开折叠" },
      { "zm", desc = "折叠一层" },
      { "zM", desc = "关闭所有折叠" },
      { "zr", desc = "展开一层" },
      { "zR", desc = "展开所有折叠" },
      { "zd", desc = "删除折叠" },
      { "zD", desc = "递归删除折叠" },
      { "ze", desc = "滚动到光标右侧" },
      { "zs", desc = "滚动到光标左侧" },
      { "zz", desc = "滚动使光标居中" },
      { "zt", desc = "滚动使光标在顶部" },
      { "zb", desc = "滚动使光标在底部" },
      { "z.", desc = "居中光标（重绘）" },
      { "zi", desc = "切换折叠开关" },
      { "zv", desc = "显示光标所在的折叠" },
      { "zx", desc = "重新计算折叠（撤销手动折叠）" },
      { "zE", desc = "删除文件内所有折叠" },
      { "z<CR>", desc = "滚屏使光标在顶部（重绘）" },
      { "z-", desc = "滚屏使光标在底部（重绘）" },
      { "z=", desc = "拼写建议" },
      { "zg", desc = "将单词加入拼写词典" },
      { "zw", desc = "将单词标记为拼写错误" },
      { "zug", desc = "撤销单词拼写标记" },
      { "zuw", desc = "撤销单词拼写错误" },
      { "zh", desc = "向左滚动" },
      { "zl", desc = "向右滚动" },
      { "zH", desc = "向左滚动半屏" },
      { "zL", desc = "向右滚动半屏" },

      { "[", group = "[ 前缀 —— 上一个" },
      { "[d", desc = "上一个诊断" },
      { "[ ", desc = "在上一行前加空行" },

      { "]", group = "] 前缀 —— 下一个" },
      { "]d", desc = "下一个诊断" },
      { "] ", desc = "在下一行后加空行" },

      -- motions（按 d/y/c/gU/gu 等操作符后出现的动作键）
      { "w", desc = "下一个单词开头", mode = "no" },
      { "b", desc = "上一个单词开头", mode = "no" },
      { "e", desc = "下一个单词末尾", mode = "no" },
      { "W", desc = "下一个 WORD 开头", mode = "no" },
      { "B", desc = "上一个 WORD 开头", mode = "no" },
      { "E", desc = "下一个 WORD 末尾", mode = "no" },
      { "ge", desc = "上一个单词末尾", mode = "no" },
      { "gE", desc = "上一个 WORD 末尾", mode = "no" },
      { "0", desc = "行首", mode = "no" },
      { "$", desc = "行尾", mode = "no" },
      { "^", desc = "行首非空白字符", mode = "no" },
      { "gg", desc = "第一行", mode = "no" },
      { "G", desc = "最后一行", mode = "no" },
      { "%", desc = "匹配括号", mode = "no" },
      { "h", desc = "左", mode = "no" },
      { "j", desc = "下", mode = "no" },
      { "k", desc = "上", mode = "no" },
      { "l", desc = "右", mode = "no" },
      { "/", desc = "向前搜索", mode = "no" },
      { "?", desc = "向后搜索", mode = "no" },
      { ";", desc = "重复上次 f/t", mode = "no" },
      { ",", desc = "往回重复上次 f/t", mode = "no" },
      { "{", desc = "上一个空行", mode = "no" },
      { "}", desc = "下一个空行", mode = "no" },
      { "f", desc = "跳到指定字符", mode = "no" },
      { "F", desc = "往回跳到指定字符", mode = "no" },
      { "t", desc = "跳到指定字符前", mode = "no" },
      { "T", desc = "往回跳到指定字符前", mode = "no" },

      -- text objects（d/y/c 后可选的文本对象）
      { "a", group = "包围（含空白）", mode = "xo" },
      { "i", group = "内部（不含空白）", mode = "xo" },

      -- <C-w> 窗口操作
      { "<C-w>", group = "窗口操作" },
      { "<C-w>s", desc = "水平切分窗口" },
      { "<C-w>v", desc = "垂直切分窗口" },
      { "<C-w>q", desc = "关闭窗口" },
      { "<C-w>o", desc = "只保留当前窗口" },
      { "<C-w>h", desc = "切换到左窗口" },
      { "<C-w>j", desc = "切换到下窗口" },
      { "<C-w>k", desc = "切换到上窗口" },
      { "<C-w>l", desc = "切换到右窗口" },
      { "<C-w>w", desc = "循环切换窗口" },
      { "<C-w>x", desc = "交换当前窗口和下一个" },
      { "<C-w>=", desc = "所有窗口等高/等宽" },
      { "<C-w>_", desc = "最大化窗口高度" },
      { "<C-w>|", desc = "最大化窗口宽度" },
      { "<C-w>+", desc = "增加窗口高度" },
      { "<C-w>-", desc = "减少窗口高度" },
      { "<C-w>>", desc = "增加窗口宽度" },
      { "<C-w><", desc = "减少窗口宽度" },
      { "<C-w>T", desc = "移到新标签页" },
      { "<C-w>H", desc = "窗口移到最左" },
      { "<C-w>J", desc = "窗口移到最下" },
      { "<C-w>K", desc = "窗口移到最上" },
      { "<C-w>L", desc = "窗口移到最右" },

      -- 其他导航（H/L 已被 bufferline 覆盖为切换缓冲区）
      { "M", desc = "光标到窗口中间行", mode = "n" },
    },
  },
}
